### ISSUE TITLE
TODO AFTER FINAL

### ISSUE THREAD

**Issue by luorui93** [RIVeR-Lab/avatar_interaction#3]
**Improvements:**
- [ ] Modulize current NDI (video + audio) code, probably written in c++ and use OOP.
- [x] Auto find snd device 
- [ ] Documentation
- [ ] NDI with GPU encoding/decoding 

**New features:**
- [ ] UI
- [ ] Watchdog system
- [ ] VR 
- [ ] WebRTC
- [ ] Shared control in teleoperation
